name: Elixir Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hexpm/elixir:1.12.1-erlang-24.0.1-ubuntu-focal-20210325

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Retrieve PLT Cache

        uses: actions/cache@v2.1.5
        id: plt-cache
        with:
          path: priv/plts
          key: elixir:1.12.1-erlang-24.0.1-ubuntu-focal-20210325-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-v3

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Pull Elixir Submodule
        run: |
          git submodule init
          git pull --recurse-submodules
          git submodule update --remote --recursive
        
      - name: Run Tests
        run: mix test --exclude external

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

      - name: Run dialyzer
        run: mix dialyzer
